from python:3.10-slim

WARKDIR /app

Copy requirements.txt .
RUN pip install -no-cache-dir -r requirements.txt

COPY . .

#entrenar y genera el artefacto en el build
RUN python train.py

EXPOSE 8000

CMD ["unicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]